spring:
  datasource:
    url: jdbc:mysql://47.104.210.228:3306/workgo_0115?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8
    username: ty
    password: ty@2018.com
    driver-class-name: com.mysql.cj.jdbc.Driver


