server:
  port: 8080      #配置环境路径名
  servlet:
    context-path: /payment

spring:
  datasource:
    url: jdbc:mysql://47.104.210.228:3306/creams3?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8
    username: ty
    password: ty@2018.com
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    allowRequestOverride: false
    allowSessionOverride: false
    cache: true
    checkTemplateLocation: true
    contentType: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    exposeSpringMacroHelpers: false
    suffix: .html
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
    settings:
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

#  cache:
#    type: CAFFEINE
#    cache-names: payment
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=1s #10分钟失效
#      #,refreshAfterWrite=5s

client_id: e53693a9c728a9790489ed73de460a45
client_secret: f2c2aea44a664582311b0044d45670ef

#数据中心请求地址
IPPort: http://120.27.219.194:8080

#获取token
getToken: /dataservices/oauth/token


